# Generated by Django 6.0.6 on 2026-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='primaryCategory',
            field=models.IntegerField(null=True),
        ),
    ]
