# Generated by Django 6.0.6 on 2026-08-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id_ingredient',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
