# Generated by Django 6.0.6 on 2026-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_remove_ingredient_idingredientcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='idIngredient',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
