# Generated by Django 6.0.6 on 2026-07-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_idingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_size',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
