# Generated by Django 6.0.6 on 2026-07-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
