# Generated by Django 6.0.6 on 2026-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_categories',
            field=models.ManyToManyField(blank=True, to='recipes.recipecategory'),
        ),
    ]
